---
title: "Classification"
author: "Kiwoon Hong"
format:
  html:
    embed-resources: true
toc: true
---

## Global Settings

```{r load-packages, message = FALSE, warning=FALSE}
knitr::opts_chunk$set( echo = TRUE,
                       fig.width = 7,
                       fig.asp = 0.618,
                       fig.retina = 3,
                       fig.align = "center", dpi = 300
                       )

### Load packages
if (!require("pacman"))
  install.packages("pacman")
pacman::p_load(tidyverse,here, class, caret,
               gmodels, klaR, pROC)
ggplot2::theme_set(ggplot2::theme_minimal
                   (base_size = 14))

###Load data
songs <- read.csv(here("data","spotify_songs.csv"))
```

## Classification - KNN

### Data Wrangling
```{r}
#| label: Data Wrangling
#| message: false
#| warning: false

###View data structure & statistics
glimpse(songs)
unique(songs$playlist_genre)

###Omit NA data, convert a label column to factor
songs <- songs |>
  na.omit()|>
  mutate(playlist_genre = as.factor(playlist_genre))

###selecting Input and output from our Data
songsinput <- songs |>
  dplyr::select(-c(1:11))
songsoutput <- songs |>
  dplyr::select(10)

###Normalizing input data
nomsongsinput <- songsinput |>
  mutate(across(everything(), ~ (.-min(.))/(max(.)-min(.))))
df <- cbind(songsoutput, nomsongsinput)
```

### Run KNN
```{r}
#| label: Run KNN
#| message: false
#| warning: false

### Splitting data into train set and test set(70:30)
set.seed(123)
idx <- sample(x = c("train", "test"),
              size = nrow(df),
              replace = TRUE,
              prob = c(7, 3))
train <- df[idx == "train", ]
test <- df[idx == "test", ]


### Extract the input and output variables for training and testing sets
train_input <- train[, -1]
train_output <- train$playlist_genre
test_input <- test[, -1]  
test_output <- test$playlist_genre

###Setting K-value
k_values <- 1:50

### Initialize variables to store accuracy values
accuracy_values <- numeric(length(k_values))

### Iterate over different values of k
for (i in k_values) {
  k <- k_values[i]
  
  ### Run KNN
  knn_predictions <- knn(train = train_input,
                         test = test_input,
                         cl = train_output,
                         k = k)
  
  ### Calculate accuracy
  accuracy_values[i] <- sum(knn_predictions == test_output) / length(test_output)
}
```

### Model performance & Visualization
```{r}
#| label: Model performance & Visualization
#| message: false
#| warning: false

### Create the confusion matrix
CrossTable(x = test_output, y = knn_predictions,
           prop.chisq = FALSE)

### Visualize the plot for accuracy based on K value
plot_data <- data.frame(k = k_values, accuracy = accuracy_values)
ggplot(plot_data, aes(x = k, y = accuracy)) +
  geom_line() +
  geom_point(size = 2) +
  geom_point(data = plot_data |> filter(k == 40 ), color = "red", size =2) +
  geom_label(aes( x=40, y=0.47, label="Accuracy = 0.466133"),                  
             color="#FF6666", 
             size=5 , angle=45, fontface="bold" )
  labs(title = "Accuracy based on K value",
       x = "k",
       y = "Accuracy")

print(paste("Max Accuracy:", max(accuracy_values)))
```

## Classification - KNN_Tuned

### Data Wrangling_Tuned
```{r}
#| label: Data Wrangling_Tuned
#| message: false
#| warning: false

###selecting Input and output from our Data
###Tuning - Exclude less genre-relevant elements
songsinputT <- songs |>
  dplyr::select(-c(1:11, 14, 15, 23))
songsoutput <- songs |>
  dplyr::select(10)

###Normalizing input data
nomsongsinputT <- songsinputT |>
  mutate(across(everything(), ~ (.-min(.))/(max(.)-min(.))))
dfT <- cbind(songsoutput, nomsongsinputT)
```

### Run KNN_Tuned
```{r}
#| label: Run KNN_Tuned
#| message: false
#| warning: false

### Splitting data into train set and test set(70:30)
set.seed(123)
idx <- sample(x = c("train", "test"),
              size = nrow(dfT),
              replace = TRUE,
              prob = c(7, 3))
trainT <- dfT[idx == "train", ]
testT <- dfT[idx == "test", ]


### Extract the input and output variables for training and testing sets
train_inputT <- trainT[, -1]
train_outputT <- trainT$playlist_genre
test_inputT <- testT[, -1]  
test_outputT <- testT$playlist_genre

###Setting K-value
###Tuning - Extend K-value from 50 to 100
k_valuesT <- 1:100

### Initialize variables to store accuracy values
accuracy_valuesT <- numeric(length(k_valuesT))

### Iterate over different values of k
for (i in k_valuesT) {
  kT <- k_valuesT[i]
  
  ### Run KNN
  knn_predictionsT <- knn(train = train_inputT,
                         test = test_inputT,
                         cl = train_outputT,
                         k = kT)
  
  ### Calculate accuracy
  accuracy_valuesT[i] <- sum(knn_predictionsT == test_outputT) / length(test_outputT)
}
```

### Model performance & Visualization_Tuned
```{r}
#| label: Model performance & Visualization
#| message: false
#| warning: false

### Create the confusion matrix
CrossTable(x = test_outputT, y = knn_predictionsT,
           prop.chisq = FALSE)

### Visualize the plot for accuracy based on K value
plot_dataT <- data.frame(k = k_valuesT, accuracy = accuracy_valuesT)
ggplot(plot_dataT, aes(x = k, y = accuracy)) +
  geom_line() +
  geom_point(size = 2) +
  geom_point(data = plot_dataT |> filter(k == 43 ), color = "red", size =2) +
  geom_label(aes( x=43, y=0.47, label="Accuracy = 0.4654146"),                  
             color="#FF6666", 
             size=5 , angle=45, fontface="bold" )
  labs(title = "Accuracy based on K value - Tuned model",
       x = "k",
       y = "Accuracy")

print(paste("Max Accuracy:", max(accuracy_valuesT)))
```

## Classification - naive Bayes
```{r}
#| label: Classification - naive Bayes
#| message: false
#| warning: false
set.seed(1234)
idx <- sample(x = c("train", "test"),
              size = nrow(df),
              replace = TRUE,
              prob = c(7, 3))
train <- df[idx == "train", ]
test <- df[idx == "test", ]

nb_model <- NaiveBayes(playlist_genre ~ ., data = train)

predictions <- predict(nb_model, test)

```

### Model performance & Visualization
```{r}
#| label: Model performance & Visualization
#| message: false
#| warning: false

### Create the confusion matrix

conf_matrix <- table(Actual = test$playlist_genre,
                     Predicted = predictions$class)
conf_matrix

#Calculate accuracy and error rate
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
print(paste("Accuracy:", accuracy))

error_rate <- 1 - accuracy
print(paste("Error Rate:", error_rate))

conf_matrix_df <- as.data.frame.matrix(conf_matrix)

### Create ROC curve
roc_curve <- roc(test$playlist_genre, as.numeric(predictions$class))
auc_value <- auc(roc_curve)
plot(roc_curve, main = "ROC Curve", col = "steelblue", lwd = 2)
text(0.8, 0.2, paste("AUC =", round(auc_value, 2)), col = "red", cex = 1.2)


```
